WIP:Address module add api documentation[MAD-8825]
nexcess/nexcess-api-docs pull request #36
Opened 2021-10-18 15:19 UTC by Neeraja82

WIP:Address module add api documentation[MAD-8225]

[MAD-8225]: https://liquidweb.atlassian.net/browse/MAD-8225?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2021-10-18 15:45 UTC, adrian-enspired requested changes

2021-10-18 15:45 UTC, adrian-enspired commented on address/add.md
> +- string `address1` (required): address1; must contain a single line of printable characters only
Make the description more readable for clients. suggest:

> address line 1; must contain a single line of text

use "text" instead of "printable characters only" for all descriptions.

2021-10-18 15:45 UTC, adrian-enspired commented on address/add.md
> +- string `email` (required): Invalid e-mail
suggest

> a valid, verifiable email address

2021-10-18 15:45 UTC, adrian-enspired commented on address/add.md
> +- string `first_name` (required): first_name; must contain a single line of printable characters only
suggest

> addressee's first name; ...

similar for last name below

2021-10-18 15:45 UTC, adrian-enspired commented on address/add.md
> +- string `phone` (optional): phone; must contain a single line of printable characters only
> phone number; ...

> cell phone number; ...

> fax number; ...

for the descriptions for each of these, instead of "printable characters ..." please use

> E_164 format preferred

2021-10-18 15:45 UTC, adrian-enspired commented on address/add.md
> +  -d '{"address1":"21700 Melrose Ave","address2":"21700 Melrose Ave","country":"US","state":"MI","zip":"48075","type":"billing","city":"Southfield","first_name":"first name","last_name":"last name","
please format the json example so it's easier to read.
```
  - d '{
      "address1":"21700 Melrose Ave",
      "country":"US",
      . . .
    }'
```
also, 
- omit the optional `address2` input here, it is incorrect
- use a fake first_name, last_name in the example
- don't use the nocworx-dev email address; suggest `support@nexcess.net`

2021-10-18 15:45 UTC, adrian-enspired commented on address/add.md
> +Served-By: nwdev-web01-int
remove the `Server`, `X-Powered-By`, and `Served-By` headers from all examples

2021-10-18 17:16 UTC, Neeraja82 commented on address/add.md
> +- string `email` (required): Invalid e-mail
Changed, please review. Seems like need to add `LG_422_INVALID_EMAIL` in translations file as existing translations file there is LG_INVALID_EMAIL

2021-10-18 17:16 UTC, Neeraja82 commented on address/add.md
> +- string `first_name` (required): first_name; must contain a single line of printable characters only
Changed for both first_name and last_name, please review.

2021-10-18 17:16 UTC, Neeraja82 commented on address/add.md
> +- string `phone` (optional): phone; must contain a single line of printable characters only
Changed for all the above number types, please review.

2021-10-18 17:17 UTC, Neeraja82 commented on address/add.md
> +Served-By: nwdev-web01-int
Added as it was there in exiting script generated one. Now removed, as suggested. Please review.

2021-10-19 13:29 UTC, adrian-enspired commented on address/add.md
> +  -d '{"address1":"21700 Melrose Ave","address2":"21700 Melrose Ave","country":"US","state":"MI","zip":"48075","type":"billing","city":"Southfield","first_name":"first name","last_name":"last name","
> typo

yep

2021-10-19 14:01 UTC, adrian-enspired commented on address/delete.md
> +logged-in users
should be `address delete`

2021-10-19 14:01 UTC, adrian-enspired commented on address/edit.md
> +logged-in users
should be `address edit`

2021-10-19 14:01 UTC, adrian-enspired commented on address/list.md
> +logged-in users
should be `address view`

2021-10-19 14:01 UTC, adrian-enspired commented on address/lookup-phone-number.md
> +logged-in users
should be `address view`

2021-10-19 14:02 UTC, adrian-enspired commented on address/show.md
> +logged-in users
should be `address view`

2021-10-19 14:03 UTC, adrian-enspired commented on address/list.md
> +  -H "Accept: application/json" \
no trailing `\`

2021-10-19 14:04 UTC, adrian-enspired commented on address/show.md
> +  -d '{
no request payload here

2021-10-19 14:04 UTC, adrian-enspired commented on address/lookup-phone-number.md
> +  -d '{
no request payload here

2021-10-19 14:05 UTC, adrian-enspired commented on address/edit.md
> +    "id":"1234",
the `id` doesn't go in the request payload (it's in the URI)

2021-10-19 14:05 UTC, adrian-enspired commented on address/delete.md
> +  -d '{
no request payload here

2021-10-19 14:09 UTC, adrian-enspired commented on address/lookup-phone-number.md
> +- string `number` (required): phone number; must contain E_164 format
correction (my fault), it's `E.164`, not `E_164`.

> phone number, in E.164 format

2021-10-19 14:13 UTC, adrian-enspired commented on address/lookup-phone-number.md
> +{ "number": +18666392377, "identity": "address:phone (pending)" }"
you can use this example response:
```
{
    "callerName": null,
    "countryCode": "US",
    "phoneNumber": "+18666392377",
    "nationalFormat": "(866) 639-2377",
    "carrier": null,
    "addOns": null,
    "url": "https://lookups.twilio.com/v1/PhoneNumbers/+18666392377"
}
```

2021-10-19 14:14 UTC, adrian-enspired commented on address/show.md
> +{ "id": 1234, "identity": "Nexcess Staff" }"
the example needs to have the full "show" payload

2021-10-19 14:16 UTC, adrian-enspired commented on address/list.md
> +{ "id": 1234, "identity": "Nexcess Staff" }"
this example needs to show the "list" payload. include only one item, and then put `, . . .` at the end to imply there can be more. for example:
```
[
  {
    "id": 12345,
    "foo": "bar,
    "baz": 42,
    "etc.": "hello!"
  },

  . . .
]
```

2021-10-20 12:03 UTC, Neeraja82 commented on address/delete.md
> +- int `id` (required): id; must be integer
Modified for edit and delete doc's also, please review.

2021-10-20 12:04 UTC, Neeraja82 commented on address/list.md
> +## address:list
Included list filter options(not sure whether to implement for match, sort and range filters.

2021-10-20 12:04 UTC, Neeraja82 commented on address/lookup-phone-number.md
> +This task is queued, meaning it will be completed out-of-band from the current request. The response payload will describe the requested task, and will also include a Location header that can be poll
Removed `queued_description' from list.md and lookup-phone-number.md, but not from the shared script as I ran manually that script to get skeleton file.

2021-10-20 12:04 UTC, Neeraja82 commented on address/show.md
> +This task is queued, meaning it will be completed out-of-band from the current request. The response payload will describe the requested task, and will also include a Location header that can be poll
Removed `queued_description' from lookup-phone-number.md, but not from the shared script as I ran manually that script to get skeleton file.

2021-10-20 12:04 UTC, Neeraja82 commented on address/delete.md
> +logged-in users
Modified, please review.

2021-10-20 12:05 UTC, Neeraja82 commented on address/lookup-phone-number.md
> +logged-in users
Modified, please review.

2021-10-20 12:05 UTC, Neeraja82 commented on address/show.md
> +logged-in users
Modified, please review.

2021-10-20 12:05 UTC, Neeraja82 commented on address/list.md
> +  -H "Accept: application/json" \
Removed, please review.

2021-10-20 12:05 UTC, Neeraja82 commented on address/delete.md
> +  -d '{
Removed, please review.

2021-10-20 12:05 UTC, Neeraja82 commented on address/show.md
> +{ "id": 1234, "identity": "Nexcess Staff" }"
Added complete show payload response. Please review.

2021-10-20 14:33 UTC, adrian-enspired commented on address/add.md
> +address edit
did you change the template?  template should look like
```
#### Access
<?= $access ?> permissions
```
...and then you define `$access = "address edit";`, etc., for each page

2021-10-20 14:42 UTC, adrian-enspired commented on address/list.md
> +## address:list
they'd all be done the same way as the filter options. base them on the values available in the `MATCH_BY`, `SORT_BY`, `RANGE_BY` constants on the concrete input class.

for the descriptions,
- `sort`: "sort list by {field}"
- `match`: "match against {field} value"
- `range`: "find {field} values within <minimum>..<maximum> range"

2021-10-20 14:42 UTC, adrian-enspired commented on address/list.md
> +- string `filter[id]` (optional): filter list by id
should by `integer`

> filter list by system ID

2021-10-20 14:44 UTC, adrian-enspired commented on address/list.md
> +**Success Response** (request was accepted for processing): success
sorry, i meant the _description_ part should be "success." so it would render like

> **Success Response** (success): 200 OK

2021-10-20 14:45 UTC, adrian-enspired commented on address/list.md
> +HTTP/1.1 success
this should remain `200 OK`

2021-10-20 17:06 UTC, Neeraja82 commented on address/list.md
> +**Success Response** (request was accepted for processing): success
Changed, please review.

2021-10-20 17:06 UTC, Neeraja82 commented on address/list.md
> +HTTP/1.1 success
Changed, please review.

2021-10-21 16:44 UTC, merged