App module api documentation for list and show[MAD-8830]
nexcess/nexcess-api-docs pull request #39
Opened 2021-10-28 10:01 UTC by Neeraja82

App module api documentation for list and show[MAD-8830]

[MAD-8830]: https://liquidweb.atlassian.net/browse/MAD-8830?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2021-11-02 12:43 UTC, adrian-enspired requested changes

2021-11-02 12:43 UTC, adrian-enspired commented on app/list.md
> +- integer `match` (optional): match against id value
should be match[name] and match[version]

2021-11-02 12:43 UTC, adrian-enspired commented on app/list.md
> +- integer `range` (optional): find id values within .. range
should be range[type], [id], [name], and [version]

2021-11-02 12:43 UTC, adrian-enspired commented on app/list.md
> +$ curl -i -X GET "$PORTAL_API_URL/v1/app" \
`-X GET` is unnecessary

2021-11-02 12:43 UTC, adrian-enspired commented on app/list.md
> +  -H "Content-type: application/json" \
there's no request body in this example, so content-type is not needed

2021-11-02 12:43 UTC, adrian-enspired commented on app/list.md
> +Location: /v1/app
there shouldn't be a `Location` header in this response (did you see one?)

2021-11-02 12:43 UTC, adrian-enspired commented on app/list.md
> -**Failure Response** (bad range/page number/page size): 416 Requested Range Not Satisfiable
should not be removed

please review other "list" endpoints already merged - they can all return `416`

2021-11-02 12:43 UTC, adrian-enspired commented on app/show.md
> +  -H "Accept: application/json" \
no trailing `\`

2021-11-02 12:43 UTC, adrian-enspired commented on app/show.md
> +  -H "Content-type: application/json" \
no request body, so no `content-type`

2021-11-02 16:10 UTC, Neeraja82 commented on app/show.md
> +  -H "Accept: application/json" \
Removed, please review.

2021-11-02 16:11 UTC, Neeraja82 commented on app/show.md
> +  -H "Content-type: application/json" \
Removed, please review.

2021-11-03 13:26 UTC, adrian-enspired approved these changes

2021-11-03 13:26 UTC, merged