Api Token module api documentation[MAD-8829]
nexcess/nexcess-api-docs pull request #41
Opened 2021-11-02 12:49 UTC by Neeraja82

Api Token module api documentation[MAD-8829]

2021-11-03 01:32 UTC, Neeraja82 commented
I will recheck all the files once again and make changes, based on the review comments received for App Module

2021-11-03 10:41 UTC, Neeraja82 commented
Pushed some changes. Please review.

2021-11-08 08:37 UTC, ppf approved these changes
for me looks ok

2021-11-11 13:51 UTC, adrian-enspired requested changes

2021-11-11 13:51 UTC, adrian-enspired commented on api-token/add.md
> +This task is queued, meaning it will be completed out-of-band from the current request. The response payload will describe the requested task, and will also include a Location header that can be poll
this endpoint is an exception to the rule - it is **not** queued; the caller must wait for the response.
remove this text.

2021-11-11 13:51 UTC, adrian-enspired commented on api-token/add.md
> -The new api token is returned in the response payload. This is the only time it will be accessible to the user; it will never be displayed again.
this needs to be restored under the endpoint description above.

2021-11-11 13:51 UTC, adrian-enspired commented on api-token/add.md
> +api-token edit
access is "logged-in users" (anyone can create an api token for themselves, there is no special permission required).

2021-11-11 13:51 UTC, adrian-enspired commented on api-token/add.md
> +- string `name` (required): name; must contain a single line of text
let's say "name for the new token"

2021-11-11 13:51 UTC, adrian-enspired commented on api-token/add.md
> +    "name":"Example, Inc."
the token name is for the user to be able to tell multiple api tokens apart, so let's choose a name that makes sense in that regard. maybe something like "laptop".

2021-11-11 13:51 UTC, adrian-enspired commented on api-token/add.md
> +Location: /v1/api-token
this shouldn't send a `Location` header. did you test and see one?

2021-11-11 13:51 UTC, adrian-enspired commented on api-token/add.md
> +  "identity": "Example, Inc.",
change example name as described above

2021-11-11 13:51 UTC, adrian-enspired commented on api-token/add.md
> +  "token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ2ZXIiOiIyIiwiaWF0IjoxNjM1ODUwMDA3LCJqdGkiOiIzYzAzNjE0NS1iYjE0LTRlZjAtOWIwNy1mN2JkNWU4NDEwYmQiLCJzdWIiOiJ7XCJleHRyYW5ldFwiOntcImNsaWVudFwiOjM4MTE0LF
truncate this for the example. leave 10 characters or so at the beginning/end and put " ... veryLongAuthToken ..." in the middle.

2021-11-11 13:51 UTC, adrian-enspired commented on api-token/delete.md
> +api-token delete
as with create, anyone can delete their own tokens so long as they're logged in. should be "logged-in users".

2021-11-11 13:51 UTC, adrian-enspired commented on api-token/edit.md
> +    "id":"4",
the token `id` is not passed in the request body; it must be in the URL.

2021-11-11 13:51 UTC, adrian-enspired commented on api-token/edit.md
> +    "name":"Example, Inc"
let's use a more descriptive example name, e.g., "workstation".

2021-11-11 13:51 UTC, adrian-enspired commented on api-token/edit.md
> +$ curl -i -X POST "$PORTAL_API_URL/v1/api-token" \
URL should be `"$PORTAL_API_URL/v1/api-token/$TOKEN_ID"`

2021-11-11 13:51 UTC, adrian-enspired commented on api-token/edit.md
> +**Success Response** (request was created for processing): 201 Created
should be "request was accepted for processing"
and "202 Accepted"

2021-11-11 13:51 UTC, adrian-enspired commented on api-token/edit.md
> +  "id": 5,
this is the wrong response payload. restore the original "api task" payload.

2021-11-11 13:51 UTC, adrian-enspired commented on api-token/list.md
> +api-token view
should be "logged-in users"

2021-11-11 13:51 UTC, adrian-enspired commented on api-token/edit.md
> +api-token edit
should be "logged-in users"

2021-11-11 13:51 UTC, adrian-enspired commented on api-token/list.md
> +- integer `match[id]` (optional): match against id value.
> match against system ID

2021-11-11 13:51 UTC, adrian-enspired commented on api-token/list.md
> +- string `match[name]` (optional): match against name value.
> match against token name

2021-11-11 13:51 UTC, adrian-enspired commented on api-token/list.md
> +  -H "Content-type: application/json" \
this example doesn't have a request body; `Content-type` is unneeded

2021-11-11 13:51 UTC, adrian-enspired commented on api-token/show.md
> +api-token view
should be "logged-in users"

2021-11-11 13:51 UTC, adrian-enspired commented on api-token/show.md
> +$ curl -i -X GET "$PORTAL_API_URL/v1/api-token/{id}" \
don't `-X GET` (GET is the default)

URL should be `"$PORTAL_API_URL/v1/api-token/$TOKEN_ID"`. using `$VARIABLES` allows users to easily try things out by defining those vars in their terminal, and then copy+pasting the example.

2021-11-11 13:51 UTC, adrian-enspired commented on api-token/show.md
> +Location: /v1/api-token/2
"show" endpoints do not return `Location` headers

2021-11-11 13:51 UTC, adrian-enspired commented on api-token/show.md
> +    "identity": "Example, Inc.",
use a token name that matches examples above (e.g., "laptop").

2021-11-11 16:08 UTC, Neeraja82 commented on api-token/add.md
> +This task is queued, meaning it will be completed out-of-band from the current request. The response payload will describe the requested task, and will also include a Location header that can be poll
Removed, please review. Actually referring to other PR's, which I worked I made these changes for example Address documentation PR.

2021-11-11 16:08 UTC, Neeraja82 commented on api-token/add.md
> -The new api token is returned in the response payload. This is the only time it will be accessible to the user; it will never be displayed again.
Added back, please review.

2021-11-11 16:08 UTC, Neeraja82 commented on api-token/add.md
> +api-token edit
Changed, please review. Actually referring to other PR's, which I worked I made these changes for example Address documentation PR.

2021-11-11 16:09 UTC, Neeraja82 commented on api-token/add.md
> +    "name":"Example, Inc."
Changed, please review.

2021-11-11 16:09 UTC, Neeraja82 commented on api-token/add.md
> +Location: /v1/api-token
Removed, please review. Actually referring to other PR's, which I worked I made these changes for example Address documentation PR.

2021-11-11 16:09 UTC, Neeraja82 commented on api-token/add.md
> +  "identity": "Example, Inc.",
Changed, please review.

2021-11-11 16:09 UTC, Neeraja82 commented on api-token/add.md
> +  "token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ2ZXIiOiIyIiwiaWF0IjoxNjM1ODUwMDA3LCJqdGkiOiIzYzAzNjE0NS1iYjE0LTRlZjAtOWIwNy1mN2JkNWU4NDEwYmQiLCJzdWIiOiJ7XCJleHRyYW5ldFwiOntcImNsaWVudFwiOjM4MTE0LF
Changed, please review.

2021-11-11 16:09 UTC, Neeraja82 commented on api-token/delete.md
> +api-token delete
Changed, please review.

2021-11-11 16:09 UTC, Neeraja82 commented on api-token/edit.md
> +    "id":"4",
Yes changed, please review.

2021-11-11 16:09 UTC, Neeraja82 commented on api-token/edit.md
> +    "name":"Example, Inc"
Changed, please review.

2021-11-11 16:09 UTC, Neeraja82 commented on api-token/edit.md
> +$ curl -i -X POST "$PORTAL_API_URL/v1/api-token" \
Yes, changed. Please review.

2021-11-11 16:09 UTC, Neeraja82 commented on api-token/edit.md
> +**Success Response** (request was created for processing): 201 Created
Changed, please review.

2021-11-11 16:09 UTC, Neeraja82 commented on api-token/edit.md
> +  "id": 5,
Added task api  response payload. Please review.

2021-11-11 16:09 UTC, Neeraja82 commented on api-token/list.md
> +api-token view
Changed, please review.

2021-11-11 16:09 UTC, Neeraja82 commented on api-token/edit.md
> +api-token edit
Changed, please review.

2021-11-11 16:09 UTC, Neeraja82 commented on api-token/list.md
> +- integer `match[id]` (optional): match against id value.
Changed, please review.

2021-11-11 16:09 UTC, Neeraja82 commented on api-token/list.md
> +- string `match[name]` (optional): match against name value.
Changed, please review.

2021-11-11 16:09 UTC, Neeraja82 commented on api-token/list.md
> +  -H "Content-type: application/json" \
Changed, please review.

2021-11-11 16:10 UTC, Neeraja82 commented on api-token/show.md
> +$ curl -i -X GET "$PORTAL_API_URL/v1/api-token/{id}" \
Changed, please review.

2021-11-11 16:10 UTC, Neeraja82 commented on api-token/show.md
> +Location: /v1/api-token/2
Changed, please review. Actually referring to other PR's, which I worked I made these changes for example Address documentation PR.

2021-11-11 16:10 UTC, Neeraja82 commented on api-token/show.md
> +    "identity": "Example, Inc.",
Changed, please review.

2021-11-11 16:10 UTC, Neeraja82 commented
Addressed all the review suggestions. Please review.

2021-11-12 12:03 UTC, adrian-enspired approved these changes

2021-11-12 12:03 UTC, merged