WIP:Mad 8826 affiliate module api documentation[MAD-8826]
nexcess/nexcess-api-docs pull request #42
Opened 2021-11-03 14:20 UTC by Neeraja82

WIP:Mad 8826 affiliate module api documentation[MAD-8826]

2021-11-12 10:39 UTC, Neeraja82 commented
Modified and pushed few more changes based on the MAD-8829 code review suggestions

2021-11-12 15:59 UTC, adrian-enspired requested changes

2021-11-12 15:59 UTC, adrian-enspired commented on affiliate/referral/list.md
> +  {
these payloads should look like
```json
[
  {
    "id": 5,
    "identity": "Howell Inc",
    "metadata": {
      "scope": "client",
      "uri": null
    },
    "status": "inactive",
    "referred_date": 1263829324
  },
  . . .
```

2021-11-12 15:59 UTC, adrian-enspired commented on affiliate/link/list.md
> +$ curl -i "$PORTAL_API_URL/v1/affiliate/link" \
for consistency, please make sure we use `$PORTAL_API` and `$PORTAL_KEY` everywhere.

2021-11-12 15:59 UTC, adrian-enspired commented on affiliate/referral/show.md
> +  "status": "active",
payload should look something like
```json
{
  "id": 36673,
  "identity": "Jacobs, Conn and Steuber",
  "metadata": {
    "scope": "client",
    "uri": null
  },
  "status": "active",
  "referred_date": 1462343023,
  "services": [
    {
      "id": 53721,
      "identity": "M-SIP-100 - 104.207.225.74: beyondgallery.com",
      "metadata": {
        "scope": "service",
        "uri": "/v1/service/shared/53721"
      },
      "status": "enabled",
      "state": "stable",
      "type": "shared"
    }
  ]
}
```

2021-11-12 15:59 UTC, adrian-enspired commented on affiliate/referral/show.md
> +$ curl -i "$PORTAL_API_URL/v1/affiliate/referral/{id}" \
use `$REFERRAL_ID`

2021-11-12 15:59 UTC, adrian-enspired commented on affiliate/referral/show.md
> +**Success Response** (request was accepted for processing): 200 OK
```
**Success Response** (success): 200 OK
```

2021-11-12 15:59 UTC, adrian-enspired commented on affiliate/link/show.md
> +**Success Response** (request was accepted for processing): 200 OK
```
**Success Response** (success): 200 OK
```

2021-11-12 15:59 UTC, adrian-enspired commented on affiliate/link/show.md
> +**Failure Response** (other bad input): 422 Unprocessable Entity
this endpoint won't return 422

2021-11-12 15:59 UTC, adrian-enspired commented on affiliate/referral/show.md
> +**Failure Response** (other bad input): 422 Unprocessable Entity
this endpoint won't return 422

2021-11-12 17:07 UTC, Neeraja82 commented on affiliate/referral/list.md
> +  {
Changed, please review. I think shared active status response.

2021-11-12 17:07 UTC, Neeraja82 commented on affiliate/link/list.md
> +$ curl -i "$PORTAL_API_URL/v1/affiliate/link" \
As discussed ignoring this, as the changes are not made in the script.

2021-11-12 17:07 UTC, Neeraja82 commented on affiliate/referral/show.md
> +  "status": "active",
Changed, please review. I think shared active status response.

2021-11-12 17:07 UTC, Neeraja82 commented on affiliate/referral/show.md
> +$ curl -i "$PORTAL_API_URL/v1/affiliate/referral/{id}" \
Changed, please review.

2021-11-12 17:08 UTC, Neeraja82 commented on affiliate/referral/show.md
> +**Success Response** (request was accepted for processing): 200 OK
Sorry, corrected. Please review.

2021-11-12 17:08 UTC, Neeraja82 commented on affiliate/link/show.md
> +**Success Response** (request was accepted for processing): 200 OK
Sorry, corrected. Please review.

2021-11-12 17:08 UTC, Neeraja82 commented on affiliate/referral/show.md
> +**Failure Response** (other bad input): 422 Unprocessable Entity
Removed, please review.

2021-11-16 13:38 UTC, adrian-enspired approved these changes

2021-11-16 13:38 UTC, merged