Cloud module list api documentation[MAD-8834]
nexcess/nexcess-api-docs pull request #43
Opened 2021-11-05 13:20 UTC by Neeraja82

Cloud module list api documentation[MAD-8834]

2021-11-08 08:38 UTC, ppf submitted a review, later dismissed

2021-11-10 14:50 UTC, ppf commented
looks ok for me

2021-11-12 15:46 UTC, adrian-enspired requested changes

2021-11-12 15:46 UTC, adrian-enspired commented on cloud/list.md
> +- integer `match[package_id]` (optional): match against package id value.
`match[package_id]` isn't valid; remove.
I've created a PR to remove the input itself.

2021-11-12 15:46 UTC, adrian-enspired commented on cloud/list.md
> +    "websocket_host": "jarvis01-dev.us-midwest-2.lwinternal.com"
let's remove this from the docs. we will probably remove it from the payload entirely at some point.

2021-11-12 16:33 UTC, Neeraja82 commented on cloud/list.md
> +- integer `match[package_id]` (optional): match against package id value.
Removed, please review.

2021-11-12 16:33 UTC, Neeraja82 commented on cloud/list.md
> +    "websocket_host": "jarvis01-dev.us-midwest-2.lwinternal.com"
Removed "websocket_host", please review.

2021-11-12 16:43 UTC, adrian-enspired approved these changes

2021-11-12 16:43 UTC, merged