Mad 8836 - Build Portal API Documentation: CloudServer Module
nexcess/nexcess-api-docs pull request #44
Opened 2021-11-08 11:10 UTC by ppf

2021-11-12 15:16 UTC, adrian-enspired requested changes

2021-11-12 15:16 UTC, adrian-enspired commented on cloud-server/resize.md
> +$ curl -i -X POST "$PORTAL_API_URL/v1/cloud-server/{id}/resize" \
use `$VARIABLES`

2021-11-12 15:16 UTC, adrian-enspired commented on cloud-server/show.md
> +$ curl -i "$PORTAL_API_URL/v1/cloud-server/{id}" \
use `$VARIABLES`

2021-11-12 15:16 UTC, adrian-enspired commented on cloud-server/start.md
> +$ curl -i -X POST "$PORTAL_API_URL/v1/cloud-server/{id}/start" \
use `$VARIABLES`

2021-11-12 15:16 UTC, adrian-enspired commented on cloud-server/stop.md
> +$ curl -i -X POST "$PORTAL_API_URL/v1/cloud-server/{id}/stop" \
use `$VARIABLES`

2021-11-15 09:53 UTC, ppf commented on cloud-server/add.md
>  - string `designated_ip` (optional): public IP address to assign to the new cloudserver. The IP must be available to OpenStack and not already be in use. NOTE, this functionality is exposed only via
ok, removing

2021-11-16 13:47 UTC, adrian-enspired approved these changes

2021-11-16 13:47 UTC, merged