Authentication module api documentation[MAD-8832]
nexcess/nexcess-api-docs pull request #45
Opened 2021-11-10 12:20 UTC by Neeraja82

Authentication module api documentation[MAD-8832]

2021-11-12 13:20 UTC, adrian-enspired requested changes

2021-11-12 13:20 UTC, adrian-enspired commented on authentication/generate-passphrase.md
> +authentication view
> anyone

2021-11-12 13:20 UTC, adrian-enspired commented on authentication/generate-passphrase.md
> +- integer `words` (optional): words of the password to generate.
> minimum number of words to use.

2021-11-12 13:20 UTC, adrian-enspired commented on authentication/generate-passphrase.md
> +Shows generated passphrase/password.
> Generates a secure passphrase.

2021-11-12 13:20 UTC, adrian-enspired commented on authentication/generate-passphrase.md
> +$ curl -i -X GET "$PORTAL_API_URL/v1/passphrase" \
no `-i` or `-X`

2021-11-12 13:20 UTC, adrian-enspired commented on authentication/generate-passphrase.md
> +  -H "Authorization: Bearer $PORTAL_API_KEY" \
no `Authorization`

2021-11-12 13:20 UTC, adrian-enspired commented on authentication/generate-passphrase.md
> +**Failure Response** (not logged in, expired token, etc.): 401 Unauthorized
this endpoint will not return 401 or 403

2021-11-12 13:20 UTC, adrian-enspired commented on authentication/login.md
> +# Portal: Authentication
this endpoint is meant for use by the portal; we do not want to advertise it for customer use.

remove.

2021-11-12 13:20 UTC, adrian-enspired commented on authentication/logout.md
> +# Portal: Authentication
this endpoint is meant for use by the portal; we do not want to advertise it for customer use.

remove.

2021-11-12 13:20 UTC, adrian-enspired commented on authentication/assess-passphrase.md
> +**Failure Response** (insufficient permissions): 403 Forbidden
this endpoint will not return 401 or 403

2021-11-12 13:20 UTC, adrian-enspired commented on authentication/forgot-password.md
> +# Portal: Authentication
this endpoint is meant for use by the portal; we do not want to advertise it for customer use.

remove.

2021-11-12 13:20 UTC, adrian-enspired commented on authentication/assess-passphrase.md
> +  -H "Authorization: Bearer $PORTAL_API_KEY" \
no `Authorization`

2021-11-12 13:20 UTC, adrian-enspired commented on authentication/recover-password.md
> +# Portal: Authentication
this endpoint is meant for use by the portal; we do not want to advertise it for customer use.

remove.

2021-11-15 09:22 UTC, Neeraja82 commented on authentication/assess-passphrase.md
> +## authentication:login
Changed, please review.

2021-11-15 09:22 UTC, Neeraja82 commented on authentication/assess-passphrase.md
> +Shows guessed passphrase/password.
Changed, please review.

2021-11-15 09:22 UTC, Neeraja82 commented on authentication/assess-passphrase.md
> +authentication view
Changed, please review.

2021-11-15 09:22 UTC, Neeraja82 commented on authentication/assess-passphrase.md
> +- string `passphrase` (required): guess passphrase; within "{min}..{max}" length.
Changed, please review.

2021-11-15 09:22 UTC, Neeraja82 commented on authentication/assess-passphrase.md
> +$ curl -i -X GET "$PORTAL_API_URL/v1/assess-passphrase" \
Removed and changed, please review.

2021-11-15 09:22 UTC, Neeraja82 commented on authentication/generate-passphrase.md
> +authentication view
Changed, please review.

2021-11-15 09:22 UTC, Neeraja82 commented on authentication/generate-passphrase.md
> +- integer `words` (optional): words of the password to generate.
Updated, please review.

2021-11-15 09:22 UTC, Neeraja82 commented on authentication/generate-passphrase.md
> +Shows generated passphrase/password.
Changed, please review.

2021-11-15 09:22 UTC, Neeraja82 commented on authentication/generate-passphrase.md
> +$ curl -i -X GET "$PORTAL_API_URL/v1/passphrase" \
Removed, please review.

2021-11-15 09:22 UTC, Neeraja82 commented on authentication/generate-passphrase.md
> +  -H "Authorization: Bearer $PORTAL_API_KEY" \
Removed, please review.

2021-11-15 09:22 UTC, Neeraja82 commented on authentication/generate-passphrase.md
> +**Failure Response** (not logged in, expired token, etc.): 401 Unauthorized
Removed, please review.

2021-11-15 09:22 UTC, Neeraja82 commented on authentication/login.md
> +# Portal: Authentication
Removed, please review.

2021-11-15 09:23 UTC, Neeraja82 commented on authentication/logout.md
> +# Portal: Authentication
Removed, please review.

2021-11-15 09:23 UTC, Neeraja82 commented on authentication/assess-passphrase.md
> +**Failure Response** (insufficient permissions): 403 Forbidden
Removed, please review.

2021-11-15 09:23 UTC, Neeraja82 commented on authentication/forgot-password.md
> +# Portal: Authentication
Removed, please review.

2021-11-15 09:23 UTC, Neeraja82 commented on authentication/assess-passphrase.md
> +  -H "Authorization: Bearer $PORTAL_API_KEY" \
Removed, please review.

2021-11-15 09:23 UTC, Neeraja82 commented on authentication/recover-password.md
> +# Portal: Authentication
Removed, please review.

2021-11-15 09:23 UTC, Neeraja82 commented
Addressed all review suggestions, please review.

2021-11-16 13:50 UTC, adrian-enspired approved these changes

2021-11-16 13:51 UTC, merged