Cloud account module api documentation[MAD-8835]
nexcess/nexcess-api-docs pull request #49
Opened 2021-12-01 12:24 UTC by Neeraja82

Cloud account module api documentation[MAD-8835]

2021-12-01 12:47 UTC, Neeraja82 commented
@adrian-enspired, For some api calls, not able to get response. Hence I request you to provide me sample responses, if possible.

2021-12-01 14:01 UTC, adrian-enspired requested changes

2021-12-01 14:01 UTC, adrian-enspired commented on cloud-account/show-stencil-details.md
> +{}
```json{
  "id": 9,
  "identity": "wednesday",
  "metadata": {
    "scope": "virt-guest-cloudaccount-stencil",
    "uri": "/v1/cloud-account/stencil/9"
  },
  "app_type": "wordpress",
  "app_version": "5.8.1",
  "cloud_account": {
    "id": 1206,
    "identity": "a84cb86096.100.lwdns.dev",
    "metadata": {
      "scope": "virt-guest-cloudaccount",
      "uri": "/v1/cloud-account/1206"
    },
    "status": "used",
    "state": "stable",
    "type": "account"
  },
  "name": "wednesday",
  "screenshot_url": "https://objects.liquidweb.services/mirador-dev/site/24512/virt-guest-cloudaccount-stencil-9/5089e29e-dda8-46b1-951a-b9911528efbc.png",
  "screenshot_uuid": "5089e29e-dda8-46b1-951a-b9911528efbc",
  "state": "stable",
  "stencil_date": 1638367171,
  "url": "https://objects.liquidweb.services/SZGPEA/stencils/stencil-1206-9.tgz"
}
```

2021-12-01 14:01 UTC, adrian-enspired commented on cloud-account/stencil-list.md
> +[]
```json
[
  {
    "id": 9,
    "identity": "wednesday",
    "metadata": {
      "scope": "virt-guest-cloudaccount-stencil",
      "uri": "/v1/cloud-account/stencil/9"
    },
    "app_type": "wordpress",
    "app_version": "5.8.1",
    "cloud_account": {
      "id": 1206,
      "identity": "a84cb86096.100.lwdns.dev",
      "metadata": {
        "scope": "virt-guest-cloudaccount",
        "uri": "/v1/cloud-account/1206"
      },
      "status": "used",
      "state": "stable",
      "type": "account"
    },
    "name": "wednesday",
    "screenshot_url": "https://objects.liquidweb.services/mirador-dev/site/24512/virt-guest-cloudaccount-stencil-9/5089e29e-dda8-46b1-951a-b9911528efbc.png",
    "screenshot_uuid": "5089e29e-dda8-46b1-951a-b9911528efbc",
    "state": "stable",
    "stencil_date": 1638367171,
    "url": "https://objects.liquidweb.services/SZGPEA/stencils/stencil-1206-9.tgz"
  },
  
  . . .
]
```

2021-12-02 11:43 UTC, Neeraja82 commented on cloud-account/show-eadn-account-details.md
> +- string `cloud_account_id` (optional): cloud account id; The system id of the cloud account that the eadn account belongs to.
Okay removed id and made cloud_account_id as required. Also removed id from request.

2021-12-02 11:43 UTC, Neeraja82 commented on cloud-account/show-eadn-account-details.md
> +{}
Thanks, added response payload. Please review.

2021-12-02 12:26 UTC, Neeraja82 commented on cloud-account/show-eadn-account-usage-details.md
> +- integer `id` (optional): System ID of the eadn account to edit
Removed, please review.

2021-12-02 12:42 UTC, Neeraja82 commented on cloud-account/delete-stencil.md
> +{}"
Added add stencil response payload modifying to delete instead of add. Please review.

2021-12-02 12:42 UTC, Neeraja82 commented on cloud-account/logs.md
> +      "#14 /home/nocworx/core/vendor/php-http/guzzle6-adapter/src/Client.php(56): Http\\Adapter\\Guzzle6\\Promise->wait()",
Truncated, please review.

2021-12-02 12:42 UTC, Neeraja82 commented on cloud-account/set-nickname.md
> +```
Removed, please review.

2021-12-02 12:43 UTC, Neeraja82 commented on cloud-account/show-autoscale-usage.md
> +{}
Thanks, added response payload. Please review.

2021-12-02 12:43 UTC, Neeraja82 commented on cloud-account/show-eadn-account-usage-details.md
> +{}
Thanks, added response payload. Please review.

2021-12-02 12:43 UTC, Neeraja82 commented on cloud-account/show-stencil-details.md
> +{}
Thanks, added response payload. Please review.

2021-12-02 12:43 UTC, Neeraja82 commented on cloud-account/stencil-list.md
> +[]
Thanks, added response payload. Please review.

2021-12-02 12:44 UTC, Neeraja82 commented
Addressed all review suggestions. Please review.

2021-12-07 13:23 UTC, adrian-enspired commented on cloud-account/show-eadn-account-details.md
> +eadn account view
i believe this endpoint requires `service view` permissions; please double-check

2021-12-07 13:35 UTC, adrian-enspired commented on cloud-account/show-eadn-account-usage-details.md
> +eadn account usage view
i believe "service view"

2021-12-07 13:36 UTC, adrian-enspired commented on cloud-account/show-stencil-details.md
> +stencil view
"service view"

2021-12-07 13:36 UTC, adrian-enspired commented on cloud-account/show.md
> +cloud account view
"service view"

2021-12-07 13:36 UTC, adrian-enspired commented on cloud-account/sso-url.md
> +cloud account view
"service view"

2021-12-07 13:36 UTC, adrian-enspired commented on cloud-account/stencil-list.md
> +stencil view
"service view"

2021-12-07 13:36 UTC, adrian-enspired commented on cloud-account/show-autoscale-usage.md
> +logged-in users
please double-check, i believe this is "service view"

2021-12-07 13:37 UTC, adrian-enspired commented on cloud-account/set-nickname.md
> +cloud account edit
i believe this is "service edit"

2021-12-07 13:37 UTC, adrian-enspired commented on cloud-account/logs.md
> +cloud account view
i believe this is "service view"

2021-12-07 13:37 UTC, adrian-enspired commented on cloud-account/list.md
> +cloud account view
i believe this is "service view"

2021-12-07 13:37 UTC, adrian-enspired commented on cloud-account/delete-stencil.md
> +stencil edit
i believe this is "service edit"

2021-12-07 13:37 UTC, adrian-enspired commented on cloud-account/change-php-version.md
> +cloud account edit
i believe this is "service edit"

2021-12-07 13:37 UTC, adrian-enspired commented on cloud-account/add-stencil.md
> +cloud account edit
i believe this is "service edit"

2021-12-09 10:41 UTC, Neeraja82 commented on cloud-account/add-stencil.md
> +    "name":"13b0305e17f.1700.lwdns.dev",
Changed, please review.

2021-12-09 10:41 UTC, Neeraja82 commented on cloud-account/delete-stencil.md
> +$ curl -i -X DELETE "$PORTAL_API_URL/v1/cloud-account/{account_id}/stencil/{id}" \
Removed, please review.

2021-12-09 10:41 UTC, Neeraja82 commented on cloud-account/free-trials.md
> +logged-in users
Okay changed, please review.

2021-12-09 10:41 UTC, Neeraja82 commented on cloud-account/free-trials.md
> +**Failure Response** (insufficient permissions): 403 Forbidden
Okay removed, please review.

2021-12-09 10:41 UTC, Neeraja82 commented on cloud-account/logs.md
> +**Failure Response** (insufficient permissions): 403 Forbidden
Okay added, please review.

2021-12-09 10:41 UTC, Neeraja82 commented on cloud-account/show-eadn-account-details.md
> +eadn account view
Actually I don't see any input, not sure on how to get in any other way. So changed as you suggested, please review.

2021-12-09 10:41 UTC, Neeraja82 commented on cloud-account/show-container.md
> +container view
Actually it's `CLIENT_USER_PRIV_VIEW`, changed to service view.

2021-12-09 10:41 UTC, Neeraja82 commented on cloud-account/show-stencil-details.md
> +stencil view
Changed, please review.

2021-12-09 10:41 UTC, Neeraja82 commented on cloud-account/show.md
> +cloud account view
Changed, please review.

2021-12-09 10:41 UTC, Neeraja82 commented on cloud-account/stencil-list.md
> +stencil view
Changed, please review.

2021-12-09 10:41 UTC, Neeraja82 commented on cloud-account/show-autoscale-usage.md
> +logged-in users
Actually it's CLIENT_USER_PRIV_VIEW. Changed, please review.

2021-12-09 10:41 UTC, Neeraja82 commented on cloud-account/set-nickname.md
> +cloud account edit
Changed, please review.

2021-12-09 10:41 UTC, Neeraja82 commented on cloud-account/logs.md
> +cloud account view
Okay changed, please review.

2021-12-09 10:41 UTC, Neeraja82 commented on cloud-account/list.md
> +cloud account view
Okay changed, please review.

2021-12-09 10:41 UTC, Neeraja82 commented on cloud-account/delete-stencil.md
> +stencil edit
Okay changed, please review.

2021-12-09 10:41 UTC, Neeraja82 commented on cloud-account/change-php-version.md
> +cloud account edit
Okay changed, please review.

2021-12-09 10:41 UTC, Neeraja82 commented on cloud-account/add-stencil.md
> +cloud account edit
Okay changed, please review.

2022-01-04 13:37 UTC, adrian-enspired commented on cloud-account/show-eadn-account-details.md
> +eadn account view
the Handler defines the permission it requires: https://github.com/nocworx/core/blob/master/src/Api/Portal/V1/CloudAccount/Cdn/Show.php#L61

and the resource is gotten the default way, from the HandlesEntity trait: https://github.com/nocworx/core/blob/master/src/Api/Portal/Handler/HandlesEntity.php#L228

2022-01-06 13:31 UTC, adrian-enspired requested changes

2022-01-07 10:07 UTC, Neeraja82 commented on cloud-account/change-php-version.md
> +    "identity": "Example, Inc - support@nexcess.net",
Yes changed, whereever is required. Please review.

2022-01-07 10:09 UTC, Neeraja82 commented on cloud-account/logs.md
> +**Success Response** (Error): 500 Internal Server Error
Yes, in dev displaying different from QA env. Created new cloudhost and copied log response from QA portal. Please review.

2022-01-07 10:09 UTC, Neeraja82 commented on cloud-account/list.md
> -**Parameters**:
Added, please review.

2022-01-07 10:09 UTC, Neeraja82 commented on cloud-account/add-stencil.md
> +$ curl -i -X POST "$PORTAL_API_URL/v1/cloud-account/{account_id}/stencil" \
Removed from the respective files. Please review.

2022-01-07 13:39 UTC, adrian-enspired requested changes

2022-01-07 13:39 UTC, adrian-enspired commented on cloud-account/logs.md
> +**Success Response** (Error): 500 Internal Server Error
still need to change this to say "200 OK"

2022-01-07 13:39 UTC, adrian-enspired commented on cloud-account/logs.md
> +HTTP/1.1 500 Internal Server Error
this didn't really return 500, did it?

2022-01-07 13:47 UTC, adrian-enspired approved these changes

2022-01-07 13:47 UTC, merged