Build Portal API Documentation: SshKey Module
nexcess/nexcess-api-docs pull request #50
Opened 2021-12-02 09:15 UTC by chittaranjan-behera

Build Portal API Documentation: SshKey Module

2021-12-07 13:54 UTC, adrian-enspired requested changes

2021-12-07 13:54 UTC, adrian-enspired commented on ssh-key/add.md
> +    "identity": "Nexcess Staff - nocworx-dev@nexcess.net",
use a fake customer name (Annabel was fine).

2021-12-07 13:54 UTC, adrian-enspired commented on ssh-key/delete.md
> +    "identity": "example-key - SHA256:3XTUdV3yYM/42K7a9ZP4V/XPUmeXO2/6PX1q8Ml3Mws chittaranjanbehera@it-HP-ProBook-440-G7 (RSA)",
let's cut out the middle of that.
```
"identity": "example-key - SHA256:3XTUdV3yYM/. . . (RSA)",
```

2021-12-07 13:54 UTC, adrian-enspired commented on ssh-key/delete.md
> +    "identity": "Nexcess Staff - nocworx-dev@nexcess.net",
use a fake customer name.

2021-12-07 13:54 UTC, adrian-enspired commented on ssh-key/list.md
> +    "identity": "nexcess-ssh-key - SHA256:3XTUdV3yYM/42K7a9ZP4V/XPUmeXO2/6PX1q8Ml3Mws chittaranjanbehera@it-HP-ProBook-440-G7 (RSA)",
`. . .` in the middle

2021-12-07 13:54 UTC, adrian-enspired commented on ssh-key/list.md
> +    "fingerprint": "SHA256:3XTUdV3yYM/42K7a9ZP4V/XPUmeXO2/6PX1q8Ml3Mws chittaranjanbehera@it-HP-ProBook-440-G7 (RSA)",
`. . .` in the middle

2021-12-07 13:54 UTC, adrian-enspired commented on ssh-key/list.md
> +      "identity": "Nexcess Staff - nocworx-dev@nexcess.net",
fake customer name

2021-12-07 13:54 UTC, adrian-enspired commented on ssh-key/show.md
> +  "identity": "nexcess-ssh-key - SHA256:3XTUdV3yYM/42K7a9ZP4V/XPUmeXO2/6PX1q8Ml3Mws chittaranjanbehera@it-HP-ProBook-440-G7 (RSA)",
`. . .`

2021-12-07 13:54 UTC, adrian-enspired commented on ssh-key/show.md
> +  "fingerprint": "SHA256:3XTUdV3yYM/42K7a9ZP4V/XPUmeXO2/6PX1q8Ml3Mws chittaranjanbehera@it-HP-ProBook-440-G7 (RSA)",
`. . .`

2021-12-07 13:54 UTC, adrian-enspired commented on ssh-key/show.md
> +    "identity": "Nexcess Staff - nocworx-dev@nexcess.net",
use fake customer name

2021-12-13 13:56 UTC, chittaranjan-behera commented on ssh-key/add.md
> +    "identity": "Nexcess Staff - nocworx-dev@nexcess.net",
Used fake customer name

2021-12-13 13:57 UTC, chittaranjan-behera commented on ssh-key/delete.md
> +    "identity": "example-key - SHA256:3XTUdV3yYM/42K7a9ZP4V/XPUmeXO2/6PX1q8Ml3Mws chittaranjanbehera@it-HP-ProBook-440-G7 (RSA)",
Removed the middle part.

2021-12-13 13:57 UTC, chittaranjan-behera commented on ssh-key/delete.md
> +    "identity": "Nexcess Staff - nocworx-dev@nexcess.net",
Used fake customer name

2021-12-13 13:57 UTC, chittaranjan-behera commented on ssh-key/list.md
> +    "identity": "nexcess-ssh-key - SHA256:3XTUdV3yYM/42K7a9ZP4V/XPUmeXO2/6PX1q8Ml3Mws chittaranjanbehera@it-HP-ProBook-440-G7 (RSA)",
Removed middle part

2021-12-13 13:57 UTC, chittaranjan-behera commented on ssh-key/list.md
> +    "fingerprint": "SHA256:3XTUdV3yYM/42K7a9ZP4V/XPUmeXO2/6PX1q8Ml3Mws chittaranjanbehera@it-HP-ProBook-440-G7 (RSA)",
Removed middle part

2021-12-13 13:57 UTC, chittaranjan-behera commented on ssh-key/list.md
> +      "identity": "Nexcess Staff - nocworx-dev@nexcess.net",
Used fake customer name

2021-12-13 13:57 UTC, chittaranjan-behera commented on ssh-key/show.md
> +  "identity": "nexcess-ssh-key - SHA256:3XTUdV3yYM/42K7a9ZP4V/XPUmeXO2/6PX1q8Ml3Mws chittaranjanbehera@it-HP-ProBook-440-G7 (RSA)",
Removed middle part

2021-12-13 13:58 UTC, chittaranjan-behera commented on ssh-key/show.md
> +  "fingerprint": "SHA256:3XTUdV3yYM/42K7a9ZP4V/XPUmeXO2/6PX1q8Ml3Mws chittaranjanbehera@it-HP-ProBook-440-G7 (RSA)",
Removed middle part

2021-12-13 13:58 UTC, chittaranjan-behera commented on ssh-key/show.md
> +    "identity": "Nexcess Staff - nocworx-dev@nexcess.net",
Used fake customer name

2022-05-09 19:41 UTC, adrian-enspired approved these changes

2022-05-09 19:41 UTC, merged