MAD-8849: Build Portal API Documentation: Package Module
nexcess/nexcess-api-docs pull request #62
Opened 2022-01-25 12:09 UTC by chittaranjan-behera

MAD-8849: Build Portal API Documentation: Package Module

2022-05-09 19:09 UTC, adrian-enspired requested changes

2022-05-09 19:09 UTC, adrian-enspired commented on package/addon/list.md
> +This alternate endpoint is sugar for `GET /v1/package/addon/{id}?filter[package_id]={id}&filter[type]={type}` and will serve identical responses. The `type` parameter is optional.
revert; the original description was correct

2022-05-09 19:09 UTC, adrian-enspired commented on package/addon/list.md
> +This alternate endpoint is sugar for `GET /v1/package/addon/{type}?filter[type]={type}` and will serve identical responses.
revert; the original description was correct

2022-05-10 06:27 UTC, chittaranjan-behera commented on package/addon/list.md
> +This alternate endpoint is sugar for `GET /v1/package/addon/{id}?filter[package_id]={id}&filter[type]={type}` and will serve identical responses. The `type` parameter is optional.
reverted

2022-05-10 06:27 UTC, chittaranjan-behera commented on package/addon/list.md
> +This alternate endpoint is sugar for `GET /v1/package/addon/{type}?filter[type]={type}` and will serve identical responses.
reverted to the original description

2022-05-10 13:42 UTC, merged